# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11d1751401863833237b245fce7cd0b586c93b3c68d53e62cf5100e0c0a8d9254081f2f5257e23a6d84e811e37ed27e200d751582d3f27a49252da098d047f8e

test:
  secret_key_base: 4db007a4de0807b2c1a5bce5898e275835c78c42b74ebde6a9341e4c8a89f1c42b37d22678cfda7d1f9d3946400e774f6b2fa1e8a4cbc8eae1c02a5c4b5dff62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
